version: "3.8"
# ci-dessus la version de yml avec laquelle on travaille

services:
  web:
    # IMPORTANT le  répertoire de build ci-dessous doit matcher le 1er
    # argument de volumes plus en bas
    build: .
    # build: ./djangobnb_backend

    command:
      python manage.py runserver 0.0.0.0:8000
      # - /bin/sh -c 'echo "hello $$HOSTNAME"'

      # - python manage.py runserver 0.0.0.0:8000
    volumes:
      # IMPORTANT le deuxième argument de volumes doit correspondre à ce
      # ce qu'indique ds le Dockerfile avec WORKDIR /usr/src/ par ex
      - .:/usr/src/
      # - ./djangobnb_backend/ :/usr/src/djangobnb_backend

    # ci-dessus, dit que le truc à gauche devrait faire persister ses données
    # dans le truc à droite
    ports:
      - 8000:8000
    # - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=djangobnb_db

volumes:
  postgres_data:
